### ISSUE TITLE
[Feat/TAS-26] 프로젝트 개발 환경 구축

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#1]
# ✨ Feature

## 🔎 Description
> 프로젝트의 기본 개발 환경을 구축하고, 필요한 기본 구조를 설정합니다.

## ✔️ To-do
- [x] .gitignore 파일 작성
- [x] 프로젝트 생성
- [x] Local DB 연동 (MySQL)
- [x] API 응답 포맷 작성
- [x] Exception Handler 작성
- [x] Swagger 설정
