### ISSUE TITLE
[Feat/TAS-171] 전반적인 조회 API 수정

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#112]
# ✨ Feature

## 🔎 Description
> 전반적인 조회 API를 수정합니다.

## ✔️ To-do
- [x] 테스트 사용자 인증 토큰 업데이트
- [x] 거래 조회 API에 거래 타입 추가
- [x] 순자산 비교문 추가
- [x] 손익현황 퍼센트 로직 수정
