### ISSUE TITLE
[Feat/TAS-56] 계정 카테고리 기능 구현

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#13]
# ✨ Feature

## 🔎 Description
> 계정 카테고리 기능을 구현합니다.

## ✔️ To-do
- [x] 계정 카테고리 API 설계
- [x] 계정 카테고리 서비스 로직 구현
- [x] 계정 카테고리 API 구현
- [x] Swagger로 API 문서화
