### ISSUE TITLE
[Feat/TAS-51] 계정 카테고리 기능 수정

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#23]
# ✨ Feature

## 🔎 Description
> 변경된 도메인을 바탕으로 계정 카테고리 기능의 로직을 수정합니다.

## ✔️ To-do
- [x] 계정 카테고리 API 설계
- [x] 계정 카테고리 서비스 로직 구현
- [x] 계정 카테고리 API 구현
- [x] Swagger로 API 문서화
