### ISSUE TITLE
[Deploy/TAS-28] CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#3]
# 👷‍♂️ Deploy

## 🔎 Description
> CI/CD 파이프라인을 구축합니다.

## ✔️ To-do
- [x] CI/CD 워크플로우 설정 파일 작성
- [x] Nginx 구성 파일 작성
- [x] Procfile 파일 작성
- [x] JAR 생성 관련 설정
- [x] Elastic Beanstalk 설정 파일 작성
