### ISSUE TITLE
[Feat/TAS-76] 거래 기능 구현

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#33]
# ✨ Feature

## 🔎 Description
> 거래 기능을 구현합니다.

## ✔️ To-do
- [x] 거래 API 설계
- [x] 거래 서비스 로직 구현
- [x] 거래 API 구현
- [x] Swagger로 API 문서화
