### ISSUE TITLE
[Feat/TAS-100] Swagger API 문서 정리

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#42]
# ✨ Feature

## 🔎 Description
> Swagger API 문서를 정리합니다.

## ✔️ To-do
- [x] Card DTO example
- [x] Category DTO example
- [x] Financial DTO example
- [x] Transaction DTO example
- [x] ResponseDTO example
