### ISSUE TITLE
[Feat/TAS-71] Slack API 활용하여 서버 에러 모니터링

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#43]
# ✨ Feature

## 🔎 Description
> Slack API를 활용하여 서버 에러를 모니터링합니다.

## ✔️ To-do
- [x] Slack API 의존성 추가
- [x] application.yml에 토큰, 채널명 등록
- [x] SlackService, SlackServiceUtils 구현
- [x] ExceptionAdvice에서 SlackService 호출
- [x] 테스트
  <img width="1481" alt="스크린샷 2024-01-26 오전 2 18 48" src="https://github.com/Central-MakeUs/Easybud-Server/assets/88311377/b59971d4-b8ce-461e-8d17-2f6cf28495fc">
