### ISSUE TITLE
[Feat/TAS-101] 장부 조회 API 구현

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#48]
# ✨ Feature

## 🔎 Description
> 장부 조회 API를 개발하여 가용자금, 재무 상태, 손익현황에 대한 정보를 조회할 수 있도록 합니다.

## ✔️ To-do
- [x] 장부 API 설계
- [x] 가용자금 조회 기능 구현
- [x] 재무 상태 조회 기능 구현
- [x] 손익현황 조회 기능 구현
- [x] 장부 조회 API 구현
- [x] Swagger로 API 문서화
