### ISSUE TITLE
[Feat/TAS-37] 개발 서버 RDS 연동

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#5]
# ✨ Feature

## 🔎 Description
> 개발 서버와 RDS를 연결하고 관련 설정을 작성합니다.

## ✔️ To-do
- [x] RDS 생성 및 Elastic Beanstalk 연동
- [x] dev 환경 RDS 설정 파일 작성
- [x] DB 연결 확인 API 개발
- [x] profile 환경변수 설정
- [x] test
