### ISSUE TITLE
[Feat/TAS-107] QueryDSL 적용 및 테스트 코드 작성

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#62]
# ✨ Feature

## 🔎 Description
> 정적 타입을 이용해서 쿼리를 작성해주는 QueryDSL 프레임워크를 적용합니다.

## ✔️ To-do
- [x] QueryDSL 의존성 추가
- [x] Entity에 대한 Q타입 생성
- [x] 기존 Repository 리팩토링 + 테스트 코드 작성
  - [x] TertiaryCategory 중복 검사 query
  - [x] Account 조회 query
- [x] service repository 메서드 호출 수정
