### ISSUE TITLE
[Feat/TAS-125] 카드 및 거래 API 누락 필드 추가

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#73]
# ✨ Feature

## 🔎 Description
> 카드 및 거래 API에서 누락된 필드들을 추가합니다.

## ✔️ To-do
- [x] 카드 목록 조회 api 적요 필드
- [x] 카드 생성 api 적요 필드
- [x] 재무 상태 조회 api 기초순자산 설정 여부 필드
