### ISSUE TITLE
[Docs/TAS-137] Swagger API Response 작성

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#87]
# 📄 Document

## 🔎 Description
> Swagger 문서에 API 응답 코드 예시를 작성합니다.

## ✔️ To-do
- [x] Auth API Response 작성
- [x] Card API Response 작성
- [x] Category API Response 작성
- [x] Financial API Response 작성
- [x] Transaction API Response 작성
- [x] 커스텀 어노테이션 사용해서 응답값 커스텀
- [x] API에 @ApiErrorCodeExample 적용
