### ISSUE TITLE
[Feat/TAS-160] 데이터 검증 및 조회 로직 수정

### ISSUE THREAD

**Issue by ahnsugyeong** [Central-MakeUs/Easybud-Server#96]
# ✨ Feature

## 🔎 Description
> 각종 로직을 수정하고, 데이터 검증 관련 로직을 개선합니다.

## ✔️ To-do
- [x] Swagger에 개발용 인증 토큰 추가
- [x] 거래 추가시 소분류, 카드 선택적으로 입력하도록 수정, 예외 처리
- [x] 월간 일별 손익 요약 조회 예시 수정
- [x] refresh token 관련 오류 메시지 수정
